blank_issues_enabled: false
contact_links:
  - name: Question ou discussion
    url: https://github.com/Alia-1to1code/git_learning/discussions
    about: Pour les questions générales, utilisez les Discussions GitHub