name: Hello GitHub Actions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Afficher les infos du run
        run: |
          echo "🚀 Workflow déclenché par : $GITHUB_ACTOR"
          echo "📌 Sur la branche : $GITHUB_REF_NAME"
          echo "🔑 Commit SHA : $GITHUB_SHA"
          echo "📦 Dépôt : $GITHUB_REPOSITORY"

      - name: Lister les fichiers du projet
        run: ls -la